web:
    image:  nsdont/taiga-docker
    links:
        - db
    volumes:
        - backend/settings/local.py:/taiga/backend/settings/local.py

db:
    image: postgres:9.3
    environment:
        POSTGRES_PASSWORD: taiga
        POSTGRES_USER: taiga
    volumes:
        - postgres_data:/var/lib/postgresql/data
